version: "3.9"

services:
    compile:
        image: duartej/eutelescope:latest
        volumes:
            - type: bind
              source: @CODEDIR
              target: /eudaq2/eudaq2
        entrypoint: "/bin/bash -c '. /eudaq2/ilcsoft/v01-19-02/Eutelescope/master/build_env.sh \
                     && mkdir -p /eudaq2/eudaq2/build \
                     && cd /eudaq2/eudaq2/build \
                     && rm -rf * \ 
                     && cmake .. -DBUILD_tlu=ON -DBUILD_python=ON -DBUILD_ni=ON \
                     && make -j4 install'"
    
    devcode:
        image: claralasa/eudaqv2:latest
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - type: bind
              source: @CODEDIR
              target: /eudaq2/eudaq2
        environment:
            - DISPLAY=unix${DISPLAY}
        networks:
            static_network:
                ipv4_address: 172.20.128.20
    
    devcode-p:
        image: claralasa/eudaqv2:latest
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - type: bind
              source: @CODEDIR
              target: /eudaq2/eudaq2
            - /dev/bus/usb:/dev/bus/usb
        privileged: true
        environment:
            - DISPLAY=unix${DISPLAY}
        networks:
            static_network:
                ipv4_address: 172.20.128.21
    
    runControl:
        volumes:
            - type: bind
              source: @CODEDIR
              target: /eudaq2/eudaq2
    
    logCollector:
        volumes:
            - type: bind
              source: @CODEDIR
              target: /eudaq2/eudaq2

    dataCollector:
        volumes:
            - type: bind
              source: @CODEDIR
              target: /eudaq2/eudaq2
    onlineMonitor:
        volumes:
            - type: bind
              source: @CODEDIR
              target: /eudaq2/eudaq2
    
    TLU:
        image: claralasa/eudaqv2:latest
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - /dev/bus/usb:/dev/bus/usb
            - type: bind
              source: @CODEDIR
              target: /eudaq2/eudaq2
        privileged: true
        environment:
            - DISPLAY=unix${DISPLAY}
        depends_on:
            - "runControl"
            - "logCollector"
            - "dataCollector"
            - "onlineMonitor"
        networks:
            static_network:
                ipv4_address: 172.20.128.7
        entrypoint: 
            - initialize_service.sh
            - TLU
    
    TestProducer:
        image: claralasa/eudaqv2:latest
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - type: bind
              source: @CODEDIR
              target: /eudaq2/eudaq2
        environment:
            - DISPLAY=unix${DISPLAY}
        depends_on:
            - "runControl"
            - "logCollector"
        networks:
            static_network:
                ipv4_address: 172.20.128.6
        entrypoint: 
            - initialize_service.sh
            - TestProducer

